apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - issuer.yaml
  # - sealed-secrets
  - imagestreams
namespace: apex
configMapGenerator:
  - name: auth-config
    behavior: replace
    literals:
      - hostname=auth.apex-hosted.cloud
      - frontend-url=https://apex-hosted.cloud
  - name: realm
    behavior: replace
    files:
      - files/apex.json
patchesJson6902:
  - patch: |-
      - op: replace
        path: /data/APEX_OIDC_URL
        value: https://auth.apex-hosted.cloud
    target:
      kind: ConfigMap
      name: apiserver
  - patch: |-
      - op: replace
        path: /data/DOMAIN
        value: https://api.apex-hosted.cloud
      - op: replace
        path: /data/OIDC_PROVIDER
        value: https://auth.apex-hosted.cloud
      - op: replace
        path: /data/ORIGINS
        value: https://apex-hosted.cloud
      - op: replace
        path: /data/REDIRECT_URL
        value: https://apex-hosted.cloud/#/login
    target:
      kind: ConfigMap
      name: backend-web
  - patch: |-
      - op: replace
        path: /data/DOMAIN
        value: https://api.apex-hosted.cloud
      - op: replace
        path: /data/OIDC_PROVIDER
        value: https://auth.apex-hosted.cloud
    target:
      kind: ConfigMap
      name: backend-cli
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: apiproxy
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: auth.apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: auth.apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: auth
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: frontend
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: image-registry.openshift-image-registry.svc:5000/apex/caddy
    target:
      kind: Deployment
      name: apiproxy
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: image-registry.openshift-image-registry.svc:5000/apex/apiserver
    target:
      kind: Deployment
      name: apiserver
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: image-registry.openshift-image-registry.svc:5000/apex/ipam-go
    target:
      kind: Deployment
      name: ipam
