apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ipam-go
  namespace: apex
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/apex/go-ipam:latest
      importPolicy: {}
      referencePolicy:
        type: Local
