apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiproxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        runAsUser: 1001930000
      containers:
        - name: caddy
          image: image-registry.openshift-image-registry.svc:5000/apex/caddy
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: caddyfile
