apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apiproxy
  annotations:
    cert-manager.io/issuer: letsencrypt
spec:
  tls:
    - hosts:
        - api.apex-hosted.cloud
      secretName: apex-api-cert
  rules:
    - host: api.apex-hosted.cloud
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: apiproxy
                port:
                  number: 8080
